name = "oil-trade"
main = ".output/server/index.mjs"
compatibility_date = "2024-01-01"

[vars]
API_URL = "https://api.myapp.com"
ENV = "production"

[[d1_databases]]
binding = "DB"
database_name = "oil_db"
database_id = "86041966-547a-498e-bdae-dd6d8e4e565c"
