name = "oil-app"
main = ".output/server/index.mjs"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "oil_db_test"
database_id = "86041966-547a-498e-bdae-dd6d8e4e565c"